spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}
  config:
    import: configserver:http://localhost:8888 